<a href="https://colab.research.google.com/github/Jose-Balocchi/Panaderiaa-Numpy/blob/main/04_Numpy_panaderia_core.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Lista de Precios (brownies, galletas, pastel)

In [ ]:
price = [2 , 1, 10]
type(price)

list

Lista de Cantidad (venta)

In [ ]:
quantity_sold = [17, 40, 1]
type (quantity_sold)
print(quantity_sold)

[17, 40, 1]


Lista de Costos

In [ ]:
cost = [0.25, 0.50, 5.00]
type(cost)

list

Lista de Sobras / leftovers

brownies, galletas, pastel, tartas, dulces, magdalena, barra de pan

In [ ]:
quantity_leftovers = [0, 0, 2, 1, 6, 0, 2]
type(quantity_leftovers)

list

Necesitamos calcular el ingreso por venta, pero no podemos multiplicar listas (price * quantity_sold) 

Ahora importaremos la bliblioteca Numpy

In [ ]:
import numpy as np


Ahora pasaremos las listas originales a listas (arrays) de Numpy

In [ ]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
cost_array = np.array(cost)
leftover_array = np.array(quantity_leftovers)

type(price_array)

numpy.ndarray

Ahora intentaremos multiplicar los nuevos arrays

In [ ]:
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

Ahora calcularemos el ingreso neto por item (precio - costo)
Definimos una nueva variable profit array

In [ ]:
profit_array = price_array - cost_array
print (profit_array)

[1.75 0.5  5.  ]


Identificar que elementos tienen un profit > 2 (solo el pastel)

In [ ]:
profit_array > 2

array([False, False,  True])

Como agregar elementos. Ahora agregaremos precios a nuestra lista de precios de Numpy
**brownies, galletas, pastel, tartas**

In [ ]:
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


Ahora agregaremos una serie de precios

**brownies, galletas, pastel, tartas, dulces, magdalena, barra de pan, torta**

In [ ]:
price_array = np.append(price_array, [4.5, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


Eliminar el ultimo elemento

**brownies, galletas, pastel, tartas, dulces, magdalena, barra de pan**

In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


Reemplazar elementos



In [ ]:
price_array [2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Actualizar  quantity_sold_array:  2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.  

brownies, galletas, pastel, tartas, dulces, magdalena, barra de pan

quantity_sold_array de 40 a 39.  (se cayo una galleta)

In [ ]:
print(quantity_sold)

[17, 40, 1]


In [ ]:
print(quantity_sold_array)

[17 40  1]


In [ ]:
quantity_sold_array = [17,39,1,2,3,16,5]
print (quantity_sold_array)
type(quantity_sold_array)

[17, 39, 1, 2, 3, 16, 5]


list

**Ingreso por venta por item considerando nuevos articulos**

In [ ]:
ingresos_regulares = price_array * quantity_sold_array
print(ingresos_regulares)

[34.  39.  12.  14.  13.5 48.  20. ]


**Crear leftover_array**

In [ ]:
print(leftover_array)

[0 0 2 1 6 0 2]


**Precio con 50 % de descuento para leftovers**

In [ ]:
print  (price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


**Ingresos Promocion leftovers**

In [ ]:
ponderador = 0.5
discount_price = [y * ponderador for y in price_array ]
print (discount_price)

[1.0, 0.5, 6.0, 3.5, 2.25, 1.5, 2.0]


In [ ]:
ingresos_promocion = leftover_array * discount_price
print (ingresos_promocion)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


**Ingresos Promocion total**

In [ ]:
sum(ingresos_promocion)

33.0

**Ingresos Totales**

In [ ]:
sum(ingresos_promocion) + sum(ingresos_regulares)

213.5